from __future__ import annotations

from dataclasses import asdict, dataclass
import csv
import json
import math
from pathlib import Path

import numpy as np

from core.universe_simulator import (  # noqa: E402
    derive_C1,
    derive_f_sph,
    derive_lambda_capacity,
    scale_factor_from_tau,
    tau_from_redshift,
)


ROOT = Path(__file__).resolve().parents[2]
OUTPUTS = ROOT / "outputs" / "islands"


@dataclass(frozen=True)
class IslandToyParameters:
    """Normalized black-hole island parameters derived from simulator constants."""

    c1: float = derive_C1()
    f_sph: float = derive_f_sph()
    lambda_capacity: float = derive_lambda_capacity()
    t_final: float = 0.96
    n_time: int = 240
    n_depth: int = 220
    entropy_floor: float = 0.018
    front_response_power: float = 1.0
    gate_response_power: float = 1.0

    @property
    def hawking_rate(self) -> float:
        return 1.0 + self.f_sph / 2.0

    @property
    def link_stiffness(self) -> float:
        return self.f_sph

    @property
    def core_capacity(self) -> float:
        return self.lambda_capacity

    @property
    def phase_drive(self) -> float:
        return 1.0 + self.f_sph

    @property
    def evaporation_z_final(self) -> float:
        return math.e**2 - 1.0


@dataclass(frozen=True)
class IslandPoint:
    t: float
    tau_macro: float
    tau_micro: float
    phase_coherence: float
    no_island_entropy: float
    island_entropy: float
    selected_entropy: float
    island_depth: float
    island_active: bool
    island_margin: float
    horizon_area: float
    entanglement_front: float


@dataclass(frozen=True)
class IslandSimulation:
    params: IslandToyParameters
    rows: list[IslandPoint]
    depth_grid: list[float]
    entropy_surface: list[list[float]]

    @property
    def page_time(self) -> float | None:
        active = [row.t for row in self.rows if row.island_active]
        return active[0] if active else None


def evaporation_redshift_from_time(t: float, params: IslandToyParameters) -> float:
    """Normalized evaporation coordinate mapped into the model redshift variable."""
    progress = max(0.0, min(1.0, t / params.t_final))
    return progress * params.evaporation_z_final


def horizon_area_entropy_from_tau(tau_macro: float) -> float:
    """Native model horizon-area proxy: area scales as a(tau)^2."""
    scale = scale_factor_from_tau(tau_macro)
    return scale * scale


def horizon_area_entropy(t: float, params: IslandToyParameters) -> float:
    """Normalized shrinking horizon entropy under evaporation."""
    return horizon_area_entropy_from_tau(tau_macro_from_time(t, params))


def tau_macro_from_time(t: float, params: IslandToyParameters) -> float:
    """Exterior black-hole time mapped through the model's native log horizon relation."""
    return tau_from_redshift(evaporation_redshift_from_time(t, params))


def tau_micro_from_macro(tau_macro: float) -> float:
    """Asynchronous orthogonal double-helix mirror map."""
    return -1.0 + (1.0 - tau_macro) / math.e


def phase_coherence_from_taus(tau_macro: float, tau_micro: float, params: IslandToyParameters) -> float:
    """
    Coherence generated by the macro/micro phase offset.

    The micro branch lags the macro branch by an e-weighted amount.  The
    normalized phase drive accumulates through that offset and is converted to a
    bounded coherence weight rather than imposed as a monotone front.
    """
    phase_offset = tau_macro - tau_micro
    phase = params.phase_drive * (1.0 - phase_offset)
    return 0.5 * (1.0 - math.cos(math.pi * max(0.0, min(1.0, phase))))


def entanglement_front(t: float, params: IslandToyParameters) -> float:
    """Island depth selected by double-helix phase coherence."""
    tau_macro = tau_macro_from_time(t, params)
    tau_micro = tau_micro_from_macro(tau_macro)
    coherence = phase_coherence_from_taus(tau_macro, tau_micro, params)
    return coherence**params.front_response_power


def no_island_entropy(t: float, params: IslandToyParameters) -> float:
    """
    Hawking branch from the native evaporation law.

    With the simulator's tau anchor, scale = exp(tau - 1).  For normalized
    evaporation, scale = 1 - t/t_final, so the remaining horizon-area fraction
    is scale^2 and the emitted coarse-grained entropy fraction is 1 - scale^2.
    """
    remaining_scale = max(0.0, 1.0 - t / params.t_final)
    radiation_fraction = 1.0 - remaining_scale**2
    return params.hawking_rate * radiation_fraction


def island_generalized_entropy(t: float, depth: float, params: IslandToyParameters) -> float:
    """
    Generalized entropy for one candidate island depth.

    depth=0 is the horizon-side cut; depth=1 is the deepest normalized interior.
    The first term is the boundary-area cost.  The second term is a finite core
    capacity penalty.  The third term represents the mismatch between island
    depth and the interior entanglement front.
    """
    area = horizon_area_entropy(t, params)
    front = entanglement_front(t, params)
    boundary_term = area * (1.0 - depth) ** 2
    core_term = params.core_capacity * depth**2
    tau_macro = tau_macro_from_time(t, params)
    tau_micro = tau_micro_from_macro(tau_macro)
    phase_coherence = phase_coherence_from_taus(tau_macro, tau_micro, params)
    phase_gate = 1.0 + params.f_sph * (phase_coherence**params.gate_response_power)
    matter_term = params.link_stiffness * phase_gate * (depth - front) ** 2
    return params.entropy_floor + boundary_term + core_term + matter_term


def run_island_scan(params: IslandToyParameters | None = None) -> IslandSimulation:
    if params is None:
        params = IslandToyParameters()

    times = np.linspace(0.0, params.t_final, params.n_time)
    depths = np.linspace(0.0, 1.0, params.n_depth)
    rows: list[IslandPoint] = []
    surface: list[list[float]] = []

    for t in times:
        tau_macro = tau_macro_from_time(float(t), params)
        tau_micro = tau_micro_from_macro(tau_macro)
        phase_coherence = phase_coherence_from_taus(tau_macro, tau_micro, params)
        no_entropy = no_island_entropy(float(t), params)
        island_values = np.array(
            [island_generalized_entropy(float(t), float(depth), params) for depth in depths]
        )
        idx = int(np.argmin(island_values))
        island_entropy = float(island_values[idx])
        island_depth = float(depths[idx])
        selected = min(no_entropy, island_entropy)
        rows.append(
            IslandPoint(
                t=float(t),
                tau_macro=tau_macro,
                tau_micro=tau_micro,
                phase_coherence=phase_coherence,
                no_island_entropy=no_entropy,
                island_entropy=island_entropy,
                selected_entropy=selected,
                island_depth=island_depth,
                island_active=island_entropy < no_entropy,
                island_margin=no_entropy - island_entropy,
                horizon_area=horizon_area_entropy(float(t), params),
                entanglement_front=entanglement_front(float(t), params),
            )
        )
        surface.append([float(value) for value in island_values])

    return IslandSimulation(
        params=params,
        rows=rows,
        depth_grid=[float(depth) for depth in depths],
        entropy_surface=surface,
    )


def write_island_outputs(
    simulation: IslandSimulation,
    out_dir: Path = OUTPUTS,
) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = out_dir / "black_hole_island_scan.csv"
    json_path = out_dir / "black_hole_island_scan.json"

    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(asdict(simulation.rows[0]).keys()))
        writer.writeheader()
        for row in simulation.rows:
            writer.writerow(asdict(row))

    payload = {
        "params": asdict(simulation.params),
        "page_time": simulation.page_time,
        "depth_grid": simulation.depth_grid,
        "rows": [asdict(row) for row in simulation.rows],
    }
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return csv_path, json_path


if __name__ == "__main__":
    sim = run_island_scan()
    csv_out, json_out = write_island_outputs(sim)
    print(csv_out)
    print(json_out)
