from __future__ import annotations

from pathlib import Path
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from island.islands_module.entropy_model import (  # noqa: E402
    OUTPUTS,
    IslandSimulation,
    run_island_scan,
    write_island_outputs,
)


PALETTE = {
    "paper": (248, 247, 242),
    "ink": (28, 36, 46),
    "muted": (91, 105, 116),
    "line": (203, 198, 188),
    "hawking": (45, 112, 161),
    "island": (42, 137, 97),
    "selected": (217, 151, 47),
    "horizon": (35, 43, 55),
}


def load_fonts() -> tuple[ImageFont.ImageFont, ImageFont.ImageFont, ImageFont.ImageFont]:
    # Cross-platform font search: Windows -> macOS -> Linux -> PIL default
    regular = [
        "C:/Windows/Fonts/segoeui.ttf",   # Windows
        "C:/Windows/Fonts/arial.ttf",
        "/System/Library/Fonts/Helvetica.ttc",  # macOS
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",  # Linux
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        "/usr/share/fonts/TTF/DejaVuSans.ttf",
    ]
    bold = [
        "C:/Windows/Fonts/segoeuib.ttf",  # Windows
        "C:/Windows/Fonts/arialbd.ttf",
        "/System/Library/Fonts/Helvetica.ttc",  # macOS
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",  # Linux
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
    ]

    def truetype(paths: list[str], size: int) -> ImageFont.ImageFont:
        for path in paths:
            try:
                return ImageFont.truetype(path, size)
            except OSError:
                pass
        return ImageFont.load_default()

    return truetype(bold, 28), truetype(bold, 18), truetype(regular, 14)


def map_x(t: float, left: int, right: int, sim: IslandSimulation) -> float:
    return left + (right - left) * t / sim.params.t_final


def map_y(value: float, top: int, bottom: int, max_entropy: float) -> float:
    return bottom - (bottom - top) * value / max_entropy


def render_island_scan(out_path: Path = OUTPUTS / "black_hole_island_scan.png") -> Path:
    sim = run_island_scan()
    write_island_outputs(sim)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    width, height = 1500, 900
    img = Image.new("RGB", (width, height), PALETTE["paper"])
    draw = ImageDraw.Draw(img)
    title_font, heading_font, font = load_fonts()

    draw.text((48, 34), "Black-Hole Island Emergence Toy Simulator", font=title_font, fill=PALETTE["ink"])
    draw.text(
        (50, 72),
        "Normalized entropy-boundary scan: island coherence is generated by the double-helix macro/micro phase map.",
        font=font,
        fill=PALETTE["muted"],
    )

    left, right = 90, 910
    top, bottom = 135, 490
    max_entropy = max(row.no_island_entropy for row in sim.rows) * 1.05
    draw.rectangle((left, top, right, bottom), outline=PALETTE["line"], width=1)
    draw.text((left, top - 32), "Page-curve competition", font=heading_font, fill=PALETTE["ink"])

    for frac in [0, 0.25, 0.5, 0.75, 1.0]:
        y = bottom - (bottom - top) * frac
        draw.line((left, y, right, y), fill=(225, 222, 214), width=1)
        draw.text((left - 56, y - 8), f"{max_entropy * frac:.2f}", font=font, fill=PALETTE["muted"])

    def polyline(values: list[tuple[float, float]], color: tuple[int, int, int], width_px: int) -> None:
        points = [
            (map_x(t, left, right, sim), map_y(v, top, bottom, max_entropy))
            for t, v in values
        ]
        draw.line(points, fill=color, width=width_px, joint="curve")

    polyline([(row.t, row.no_island_entropy) for row in sim.rows], PALETTE["hawking"], 3)
    polyline([(row.t, row.island_entropy) for row in sim.rows], PALETTE["island"], 3)
    polyline([(row.t, row.selected_entropy) for row in sim.rows], PALETTE["selected"], 4)

    page_time = sim.page_time
    if page_time is not None:
        x = map_x(page_time, left, right, sim)
        draw.line((x, top, x, bottom), fill=PALETTE["horizon"], width=2)
        draw.text((x + 8, top + 8), f"island emerges t={page_time:.3f}", font=font, fill=PALETTE["ink"])

    draw.text((right - 168, top + 18), "Hawking branch", font=font, fill=PALETTE["hawking"])
    draw.text((right - 168, top + 42), "Island extremum", font=font, fill=PALETTE["island"])
    draw.text((right - 168, top + 66), "Selected entropy", font=font, fill=PALETTE["selected"])

    heat_left, heat_right = 90, 910
    heat_top, heat_bottom = 590, 810
    draw.text((heat_left, heat_top - 34), "Generalized-entropy landscape S_gen(t, island depth)", font=heading_font, fill=PALETTE["ink"])
    rows = sim.entropy_surface
    flat = [value for row in rows for value in row]
    lo, hi = min(flat), max(flat)
    nx, ny = len(rows), len(sim.depth_grid)
    for ix, row in enumerate(rows):
        x0 = heat_left + (heat_right - heat_left) * ix / nx
        x1 = heat_left + (heat_right - heat_left) * (ix + 1) / nx + 1
        for iy, value in enumerate(row):
            normalized = (value - lo) / (hi - lo)
            r = int(40 + 190 * normalized)
            g = int(135 - 70 * normalized)
            b = int(95 + 60 * (1.0 - normalized))
            y1 = heat_bottom - (heat_bottom - heat_top) * iy / ny
            y0 = heat_bottom - (heat_bottom - heat_top) * (iy + 1) / ny - 1
            draw.rectangle((x0, y0, x1, y1), fill=(r, g, b))

    # Draw extremized island-depth trajectory.
    points = [
        (
            heat_left + (heat_right - heat_left) * row.t / sim.params.t_final,
            heat_bottom - (heat_bottom - heat_top) * row.island_depth,
        )
        for row in sim.rows
    ]
    draw.line(points, fill=(255, 255, 255), width=3)
    draw.line(points, fill=PALETTE["horizon"], width=1)
    draw.text((heat_right + 20, heat_top), "depth=1 interior", font=font, fill=PALETTE["muted"])
    draw.text((heat_right + 20, heat_bottom - 14), "depth=0 horizon", font=font, fill=PALETTE["muted"])

    panel_x = 990
    draw.rounded_rectangle((panel_x, 135, 1445, 455), radius=8, fill=(255, 255, 255), outline=PALETTE["line"], width=1)
    draw.text((panel_x + 18, 158), "Model Contract", font=heading_font, fill=PALETTE["ink"])
    page_row = next((row for row in sim.rows if row.island_active), None)
    lines = [
        f"C1 = {sim.params.c1:.8f}",
        f"f_sph = {sim.params.f_sph:.6f}",
        f"lambda_capacity = {sim.params.lambda_capacity:.6f}",
        f"hawking_rate = {sim.params.hawking_rate:.6f}",
        "coherence: tau_micro = -1 + (1 - tau_macro)/e",
        "Island appears only if extremized S_gen is the lower branch.",
    ]
    if page_row is not None:
        late_row = next((row for row in reversed(sim.rows) if row.island_active), page_row)
        lines.extend(
            [
                f"t_Page = {page_row.t:.3f}",
                f"tau_macro/micro = {page_row.tau_macro:.3f} / {page_row.tau_micro:.3f}",
                f"coherence: {page_row.phase_coherence:.3f} -> {late_row.phase_coherence:.3f}",
            ]
        )
    for idx, line in enumerate(lines):
        draw.text((panel_x + 18, 198 + 27 * idx), line, font=font, fill=PALETTE["muted"])

    img.save(out_path)
    return out_path


if __name__ == "__main__":
    print(render_island_scan())
